kind: Service
apiVersion: v1
metadata:
  name: php-demo-service
spec:
  selector:
    app: php-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-demo
  labels:
    app: php-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-demo
  template:
    metadata:
      labels:
        app: php-demo
    spec:
      imagePullSecrets:
      - name: devops-docker-registry
      containers:
      - name: php-demo
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8000
